# Site settings
title: Quermece do Raul Hacker Club
description: Apoie a causa e adquira produtos fofos
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loja.raulhc.cc" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Raul Hacker Club
user_description: O hacker space mais diverso do Brasil!
email: loja@raulhc.cc
twitter_username: raulhackerclub
github_username:  raulhackerclub
gplus_username:  
disqus_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: Sobre
    url: /sobre

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
